### ISSUE TITLE
Написать README.md

### ISSUE THREAD

**Issue by belkka** [monsteroko/SCPF-WA#22]
- Какие платформы поддерживает проект?
- Как собрать и запустить?

**Comment by monsteroko** [comment]
Проект поддерживает Windows/Linux, а так же  Android/Linux в тестовом режиме. 
Для сборки и запуска необходимо скачать Unity версии **не ниже**  2018.4.9f1, открыть в нём папку с проектом, и в IDE выполнить сборку при помощи пункта Build.

**Comment by belkka** [comment]
:clap: :+1: Это было быстро :)
