### ISSUE TITLE
Разбить карту

### ISSUE THREAD

**Issue by Nimpir** [monsteroko/SCPF-WA#4]
Разбить карту на регионы вместо стран, заменить столицы на подходящие места для зоны (по 1 на рагион). Общее количество зон 20-40, обсудить дополнительно.

**Comment by monsteroko** [comment]
В используемом в игре ассете есть уже встроенный редактор карты. Там же есть возможность сделать отдельные регионы или переносить столицы.
Как вариант, можно удалить стандартные страны и вместо них сделать регионы с местами для зон.
Документация на ассет с описанием данного функционала в прикреплённом к комментарию файле.
[Documentation2D.pdf](https://github.com/monsteroko/SCPF-WA/files/3340828/Documentation2D.pdf)
